models/ImageForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

class ImageForm extends Model
{
    public $imageFile;

    public function rules()
    {
        return [
            [['imageFile'], 'required'],
            [['imageFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'jpg, jpeg, png'],
        ];
    }
}

controllers/ImagesController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\services\ImageProcessor;
use app\models\ImageForm;

class ImagesController extends Controller
{
    public function actionIndex()
    {
        $model = new ImageForm();

        return $this->render('index', ['model' => $model]);
    }

    public function actionCreate()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $request= \Yii::$app->request;

        $processor = new ImageProcessor($request);

        if ($processor->run()) {
            return [
                'imageFilePath' => $processor->getImageFilePath(),
                'errors' => [],
            ];
        }
        
        return [
            'errors' => $processor->getErrors(),
        ];
    }

}

views/images/index.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Images';
?>

<div class="row images-index">
	<div class="col-md-6">
		<h1>Загрузите изображение</h1>

        <?php $form = ActiveForm::begin([
        	'action' => Url::toRoute(['images/create']),
        	'options' => ['enctype' => 'multipart/form-data'],
        	'id' => 'image-file-form',
        ]); ?>
        	<div class="loading">Идет обработка...</div>

        	<div class="form-fields">

	        	<div class="preview"></div>
	            
	            <?= $form->field($model, 'imageFile')->fileInput() ?>

	            <div class="form-group">
	                <?= Html::submitButton('Обработать', ['class' => 'btn btn-primary']) ?>
	            </div>
	        </div>

        <?php ActiveForm::end(); ?>
	</div>

	<div class="col-md-6">
		<h1>Результат</h1>
		<div id="image-file-form-result" class="preview">
			<p>Сначала загрузите изображение</p>
		</div>
	</div>
</div>